### ISSUE TITLE
Infrastructure migration

### ISSUE THREAD

**Issue by MartinPaulEve** [COPIM/open-book-collective#105]
We are hitting strange disk usage spikes on the current hosting box. We need to attempt to migrate the site to a new server. We are investigating zero-downtime solutions for this. We are also hitting challenges with Django migrations and the move of the git branch from master to main.

Steps involved:

- [x] 1. Create EBS volume
- [x] 2. Mount it
- [x] 3. Copy files onto said EBS volume
- [x] 4. Mount it over current point

Optional steps if problem persists:

- [x] 5. Create new EC2 box
- [x] 6. Basic server setup (users, packages, database)
- [x] 7. Migrate postgres
- [x] 8. Migrate nginx config
- [x] 9. Setup static serving
- [x] 10. Update DNS
- [x] 11. Certbot certificate
- [x] 12. Migrate bookstack

@joedeville for info.

**Comment by MartinPaulEve** [comment]
Initial indications are that moving the hosting to EBS block storage has succeeded. Will continue to monitor.

At the weekend, Andy and Martin will investigate ongoing git history problems in the repo.

**Comment by joedeville** [comment]
Thanks @MartinPaulEve !

**Comment by MartinPaulEve** [comment]
New EC2 box has been provisioned

**Comment by MartinPaulEve** [comment]
NGINX, postgres installed and configured

**Comment by MartinPaulEve** [comment]
Main block of server setup, security, and daemon configuration is now done. Aiming at some point this week to meet up with Andy to undertake final delicate DB migration and domain name transfer.

**Comment by MartinPaulEve** [comment]
Postgres is migrated.

**Comment by MartinPaulEve** [comment]
Static serving is now working.

**Comment by MartinPaulEve** [comment]
Certbot has issued certificates

**Comment by MartinPaulEve** [comment]
Migrations complete: watch and wait phase
