### ISSUE TITLE
Homepage quotes - slider

### ISSUE THREAD

**Issue by francescacorazza** [COPIM/open-book-collective#106]
Currently, the slider in the 'Working together' block on the homepage is not working - as there were not enough testimonials to browse, we decided to have the top right arrow linked to the Initiatives' page. 
We are now going to add a few new testimonials, so we would need to activate it again. Is that something we can change ourselves?

<img width="883" alt="Screenshot 2023-10-30 at 11 23 46" src="https://github.com/COPIM/open-book-collective/assets/120570478/efd43e25-864d-40f8-868d-e7962101f989">

**Comment by MartinPaulEve** [comment]
Unsure I understand this. At present, there are 4 testimonials that work (you can click them to see it) and a link to the initiatives page. There is scope for a max of 4 testimonials here; it's not something we can easily expand due to design/space limitations.

**Comment by joedeville** [comment]
OK, thanks and no worries. We will consider whether this is a development priority then or not and if so, will discuss in the round along with other stuff. Sorry, hard to quite remember all the various decisions that were made along the way.

**Comment by joedeville** [comment]
Closing, as clarified via creation of new issues #111 and #117
