### ISSUE TITLE
New pages to be created (various)

### ISSUE THREAD

**Issue by moananddrone** [COPIM/open-book-collective#109]
The creation of new pages to provide more information on each of these headline drivers.

**Comment by judith-fathallah** [comment]
As I wrote on the doc, suggest calling it 'stronger OA communities' or similar

**Comment by joedeville** [comment]
To be created by OBC team once #112 completed. Pages include: Prosperous OA Communities; Sustainable Funding; Robust Infrastructures; Diversity in OA; FAQs

**Comment by joedeville** [comment]
See also #107
