### ISSUE TITLE
Make site addresses and email addresses into hyperlinks

### ISSUE THREAD

**Issue by judith-fathallah** [COPIM/open-book-collective#113]
Minor point, but there are some phrases that should be hyperlinks for consistency's sake:

1) the email address info@openbookcollective.org on https://openbookcollective.org/cms/fixed_page/funding_model/
2) the same email address and https://www.rocketlawyer.co.uk on the terms of use page
3) the same email address on 'accessibility'

**Comment by joedeville** [comment]
I think we can do this ourselves, at least for now?
