### ISSUE TITLE
Catalogue: filter button oddities

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#119]
For the 'select an initiative' filter, you have to click in the main area of the filter. If you try to click on the drop down arrow, it does not respond. This is different to the sort by date filter. Tested on Chrome and Firefox

**Comment by joedeville** [comment]
(can make it seem like the button is not working at all -- as intuitively one clicks on the arrow)

**Comment by ajrbyers** [comment]
PR added.
