### ISSUE TITLE
Mobile view: Drop-down menu oddities for initiatives 

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#121]
In mobile view, when looking at an initiative page, there appears to be a drop down menu next to the initiative name, but when clicking on drop-down arrow, no submenu is shown

(A minor bug)
![Screenshot_20240204-155043~2.png](https://github.com/COPIM/open-book-collective/assets/82036056/44842c59-936a-4e53-89c1-a4d00b51d82e)

**Comment by ajrbyers** [comment]
PR added.
