### ISSUE TITLE
Mobile view: homepage bugs/wrong text

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#123]
See attached screenshots

![Screenshot_20240204-191354~2.png](https://github.com/COPIM/open-book-collective/assets/82036056/6b4a1229-fc45-47b9-9374-bf3583a21e94)

![Screenshot_20240204-190627~3.png](https://github.com/COPIM/open-book-collective/assets/82036056/5147342d-e8d6-43b0-8837-6453274c3127)

![Screenshot_20240204-183733~4.png](https://github.com/COPIM/open-book-collective/assets/82036056/dbcb7c7a-b4fb-4212-ad53-4e090b85491b)

**Comment by MartinPaulEve** [comment]
Removed funder text in mobile. Not yet deployed.

**Comment by MartinPaulEve** [comment]
Buttons re-added to mobile view. Not yet deployed.

**Comment by MartinPaulEve** [comment]
Text fill correctly (was using misnamed template tag). Not yet deployed.

**Comment by MartinPaulEve** [comment]
Deployed
