### ISSUE TITLE
Bug: changing to less frequently used currencies & button text

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#129]
When choosing less used countries (e.g. South Africa, but also Tajikistan etc), to change the currency, the site returns a ‘Server 500’ error. Which then is impossible to avoid. 

Also, the button says “Update country Update country”

**Comment by MartinPaulEve** [comment]
- [x] "Update country Update country"
- [x] Fix crash

**Comment by MartinPaulEve** [comment]
OK, I think this is fixed. Please reopen it if recurs.
