### ISSUE TITLE
Enable automatic presentations of 'portfolios' of initiatives, relevant to local interests

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#15]
As an institutional user ... 
... I would like to have displayed a preassigned ‘portfolio’ of publishers that most closely reflects my institutional objectives,priorities and budget 

... so that I can understand subscription offers relevant to me without necessarily having to assess each component offering individually.

As an OAI... 
... I would like my subscription offer to be included as part of ‘portfolios’ of publishers that closely reflects the objectives,priorities and budgets of particular institutions

**Comment by PenierI** [comment]
When we create a database of subscribers, I suspect we will do it by asking librarians to create accounts and provide  information about their institutions, who to contact etc. Could we make them indicate what research areas they are interested in so they can receive alters/offers tailored to their needs? How do we ask  them about their objectives and priorities. I am not sure what is meant by objectives and priorities. Can this information be provided in a structured way (librarians ticking items on a list/ drop down menu etc.) so tailoring the offer is automated?

**Comment by judith-fathallah** [comment]
@PenierI I think that's very reasonable, to ask them to select from a list of subject areas/themes. Priorities could be about research and teaching - like are they looking for books specifically for particular taught courses or research centers?

**Comment by joedeville** [comment]
Yes, that makes sense I think -- although I always find that checkboxes never really match my interests, so it's also about thinking about diverse/creative ways for institutions to get at some of this stuff

**Comment by judith-fathallah** [comment]
We can have text boxes for people to write in, not just checks or dropdown menus
