### ISSUE TITLE
Make legal information on OABPs available

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#17]
As a librarian or institutional decision-maker visiting an open access initiative’s profile page ...

... I want to know where the initiative is based and that legal requirements for my membership will be satisfied ...

... so that I can be sure membership complies with legal obligations the library and university are under when making procurements.

**Comment by joedeville** [comment]
Is this actually a development issue? Or is it just content?

**Comment by judith-fathallah** [comment]
Would just come under 'about us' as content I think. Though what info exactly would institutions want?

**Comment by joedeville** [comment]
I think @rupertgatti might have the clearest view on this.  Although if specific legal info is required, I think having a dedicated section prob makes sense
