### ISSUE TITLE
Agree Platform positioning statement

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#2]

**Comment by tosteiner** [comment]
Develop Positioning statement via [Wiki/Positioning Statement](https://github.com/COPIM/open-book-collective/wiki/Positioning-statement)

**Comment by judith-fathallah** [comment]
These are the original ones I came up with:

To end users including librarians:

[NAME] is a user-friendly, integrated platform to explore, discover, access and support OA monographs from a range of leading OA publishers and infrastructure providers via high-quality integrated metadata and fully searchable catalogues.
It offers a choice of flexible subscription packages, through which patrons can participate in the governance and maintenance of the platform.

To publishers: 

[NAME] is a user-friendly, integrated platform to display, promote, catalogue, organize and monetize OA monographs.
It offers a range of subscription and support packages to patrons; networking opportunities with librarians, institutions, and other end users, and customizable members’ spaces for publishers to promote their catalogues.

**Comment by tosteiner** [comment]
added @judith-fathallah 's first drafts to the [Wiki](https://github.com/COPIM/open-book-collective/wiki/Positioning-statement), suggest to continue in there with updates to these statements

**Comment by tosteiner** [comment]
@joedeville has updated the statement

One question: Joe writes

> At the heart of collective sits the Open Book Collective library membership platform.

I wonder if we need the focus on "library membership" here? What do others think?

**Comment by judith-fathallah** [comment]
@tosteiner @joedeville Maybe just call it a membership platform? Main source of revenue is likely to indeed be libraries but publishers are equally members

**Comment by joedeville** [comment]
Yes, agree @judith-fathallah @tosteiner -- just 'membership' makes sense. What do you think about the rest of the PS?

**Comment by judith-fathallah** [comment]
I made some small tweaks to it, and now I think it's good
