### ISSUE TITLE
One-stop shop for membership-related documentation

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#25]
As a librarian or institutional decision-maker visiting an open access initiative’s profile page ...

... I want documentation associated with all my memberships and payments to be accessible (eg contracts, contact details for institutions signed up to, statements ensuring legal requirements are satisfied) through a single access point ...

... so that I don’t need to keep record of multiple access points/passwords etc.

**Comment by PenierI** [comment]
This concept replicates what OA Switch Board does with respect to managing APCs (payments, compliance etc.). So their services cover the 'payment' part unless what is meant here by 'payment' is a membership fee? Switch Board has created many tutorials about how their system works, I think there are some interesting solutions that we might repurpose.

**Comment by joedeville** [comment]
Thanks Iza, this is a really good point. One for me @tosteiner and @rupertgatti to look into
