### ISSUE TITLE
Provide information on how initiatives will integrate their outputs with existing library infrastructure

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#28]
As a librarian or institutional decision-maker visiting an open access initiative’s profile page ...

...I want, for OABPs, to be able integrate open access monographs into our library systems ...

... so that our community can utilize the books (including metadata and content) within our existing systems.

**Comment by joedeville** [comment]
Done by the initiatives themselves, as part of the service they offer? Not a platform requirement?

**Comment by rupertgatti** [comment]
Maybe done through Thoth or (say) OAPEN - but may be facilitated through platform - eg notifications to enable connections to be made.

**Comment by joedeville** [comment]
Can you give a bit more detail @rupertgatti -- so when you subscribe, you might for instance receive details of how to integrate a catalogue into your library? Or do you mean subscribers get notified when there are new texts to integrate?

**Comment by tosteiner** [comment]
Presentation of details on available channels per publisher, e.g. 

* OBP is listed on OAPEN, Project MUSE, ...
* punctum is listed on x, y, z. ....
