### ISSUE TITLE
Provide libraries with strucured metadata

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#29]
As an open access book publisher (OABP)...

... I want to be able to supply metadata (eg MARC records) and ebooks to libraries ...

... so that libraries can easily integrate my content into their catalogues, digital learning environments and library ebook collections/repostories

**Comment by joedeville** [comment]
Are we expecting this to be done by the platform or by OABPs?

**Comment by tosteiner** [comment]
Might be _through_ the platform via presenation of Thoth-as-a-Service? 
Also information on the platform that points to ScholarLed OABPs that serve as initial subset of publishers to showcase Thoth

**Comment by joedeville** [comment]
This then seems to overlap with https://github.com/COPIM/open-book-collective/issues/28 ?

**Comment by judith-fathallah** [comment]
Yes agree with through the platform - OABPs would need to supply then Thoth would make sure it is all integrated/readable by the same system?

**Comment by tosteiner** [comment]
yep, that would be the idea - ScholarLed publishers are already working with the Thoth team (WP5) to get their publications into the Thoth database, and Thoth's database can then be utilized to display this publication data on the platform.

**Comment by joedeville** [comment]
I think the key thing here would not to make using THOTH a requirement for joining the platform, but to showcase the 'value add' for publishers of using THOTH and what it could do for them (potentially helped by the platform)
