### ISSUE TITLE
Articulate the ScholarLed offer as simply and precisely as possible

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#3]

**Comment by tosteiner** [comment]
Started with two documents on the Wiki:

* [[ScholarLed core]]
* [[Extended Collective]]

**Comment by tosteiner** [comment]
Added an ["Assumptions" Wiki entry](https://github.com/COPIM/open-book-collective/wiki/Assumptions) to make explicit the underlying assumptions that are informing the above-mentioned packages

**Comment by tosteiner** [comment]
Next to the Assumptions, @PenierI has created a business plan outline focusing on ScholarLed as the core offer. The first draft with comments from @rupertgatti and @tosteiner are available as a collab. document on COPIM's Nextcloud, `WP2/Platform Development/ScholarLed package` ([NC link](https://cloud.copim.ac.uk/f/84663))
