### ISSUE TITLE
Write 'About OBC' copy

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#31]

**Comment by joedeville** [comment]
Develop content via https://github.com/COPIM/open-book-collective/wiki/About-Open-Book-Collective

**Comment by judith-fathallah** [comment]
I have written initial draft on the Wiki page

**Comment by judith-fathallah** [comment]
Added some notes to the 'why support' section, but not sure what to put for publishers. Maybe a publisher would have better insight on this one
