### ISSUE TITLE
 Enable initiatives to showcase output via information added manually to the site

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#32]
As an OABP or OAI, 
 
... I want to be able to showcase my output via information I manually add to the site, because I don't use THOTH

To help me market my content to potential subscribers

**Comment by PenierI** [comment]
If we allow OABP to add MARC records manually, how do we ensure quality of that data? Or maybe this comment is about some other sort of information than metadata?

**Comment by MartinPaulEve** [comment]
Is it necessarily MARC records? If not using Thoth we could instead present a structured form in which they would have to submit such data...? Or pull from an ONIX feed?

**Comment by PenierI** [comment]
Structured form, I guess, means that there is a form to fill in. If that is a spreadsheet and not all boxes are filled, the record will be incomplete. But if that is an online form that cannot be submitted unless all necessary information is provided, that might work.
