### ISSUE TITLE
Include OBC fees in checkout process

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#40]
Currently, we simply have text noting that the OBC Supporter fee (5%) will be added at the invoicing stage, but it would be better to have this shown clearly as a line in the final quotation. It would also be important to be able to amend this fee in the backend, if we decide to change it in future.

**Comment by ajrbyers** [comment]
The main difficulty I can see with this is where you have for example:

- Package 1 £100
- Package 2 £200
- Package 3 $300

For the most part, given how its setup this probably wouldn't happen as most packages will have a GBP and USD pricing but we should consider how to handle a package that has this issue. How would it be calculated?

OBC Supporter Fee: £15 and $15 ?

**Comment by rupertgatti** [comment]
I don't believe that there is any library that will want to pay in two different currencies - so I believe the best solution to this is to ensure all quotes are in a single currency (or require a single currency selection for the site as a whole). If they really do want seperate currency payments then it could be implemented as two sepearete orders.

**Comment by ajrbyers** [comment]
> I don't believe that there is any library that will want to pay in two different currencies - so I believe the best solution to this is to ensure all quotes are in a single currency (or require a single currency selection for the site as a whole). If they really do want seperate currency payments then it could be implemented as two sepearete orders.

Regardless, if a package doesn't support a currency a user selects its going to pick a default which may result in an order having two currencies. We need to handle this on the checkout process either way as due to the way bandings were designed it is possible.
