### ISSUE TITLE
Agree list of information we want to communicate about the platform

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#5]

**Comment by tosteiner** [comment]
Partial overlaps with #4 and @judith-fathallah 's [comment ](https://github.com/COPIM/open-book-collective/issues/4#issuecomment-815918990)

**Comment by tosteiner** [comment]
Note: `WP2/Site content ideas` folder on Nextcloud, [link](https://cloud.copim.ac.uk/f/69197).

**Comment by judith-fathallah** [comment]
I've asked the mattermost channel if we are all agreed that the info on positioning statement/about us is suitable for more public communication now. Its pretty broad but just wanted to see if anyone wanted to object
