### ISSUE TITLE
Correct price bands displayed for packages

### ISSUE THREAD

**Issue by rupertgatti** [COPIM/open-book-collective#53]
Creating quotation for a mid sized PhD library for ScholaLEd Collection I generate a quote of £4600.
The price range displayed on the initiatives page shows highest price of £4300.

**Comment by joedeville** [comment]
Likely a data entry error as these prices are entered manually. I will check and amend. However this points to the fact that it would better if this price range were pulled from the backend rather than being entered manually.

**Comment by joedeville** [comment]
Created this feature request: https://github.com/COPIM/open-book-collective/issues/54

**Comment by joedeville** [comment]
Actually just ran some tests. Think this may be related to this issue: https://github.com/COPIM/open-book-collective/issues/39#issue-1488305039

**Comment by joedeville** [comment]
Worked the issue out -- it's not about currencies, but a bug which affects initiatives displayed on Support OA Initiatives (one initiative included in ScholarLed was in the package, but not visible). https://github.com/COPIM/open-book-collective/issues/59. Have solved for now by making sure no initiative is set as 'meta only', and changed the summary pricing shown
