### ISSUE TITLE
If 'meta only' is specified for an initiative, individual initiative is not viewable 

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#59]
Selecting 'meta only' makes the individual initiative disappear from the list of initiatives on Support OA Initiatives in the 
Publishers and Service Providers list. They should be visible, but it should only be possible to add them to a quote via the chosen Collection.

**Comment by ajrbyers** [comment]
Just to clarify this is not a bug. Meta Only is set for a Package, not an initiative, and the whole point is for them to _only_ appear as part of a meta package so they would not be listed as an individual package.

If this is something you want to be changed, it should be listed as a piece of future work.
