### ISSUE TITLE
Year of publication in books preview in Catalogue?

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#65]

**Comment by ajrbyers** [comment]
@joedeville can you let me know where you'd like it to appear in the list?

**Comment by joedeville** [comment]
Maybe below the title but above the list of authors @ajrbyers? If it's possible to pull just the year not the full publication date that'd be preferable

**Comment by MartinPaulEve** [comment]
Addressed in https://github.com/COPIM/intrepid/commit/6e5ecba7ceb8ccca421630bbe3240a2214483392
