### ISSUE TITLE
Set basic metadata standards for books pulled into catalogue

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#66]
Only pull books into catalogue that meet certain basic metadata standards (especially title, year, authors, cover image), to ensure consistency of appearance

**Comment by joedeville** [comment]
@MartinPaulEve & Andy: is this easy to do? If we tell you what is required and what is not, from Thoth, can a filter be created?

**Comment by ajrbyers** [comment]
Yep we should be able to filter out articles that don't meet the set criteria.
