### ISSUE TITLE
the icon images in the circles are cut off (homepage - take action section)

### ISSUE THREAD

**Issue by francescacorazza** [COPIM/open-book-collective#71]

**Comment by joedeville** [comment]
@francescacorazza can you explain this one?

**Comment by francescacorazza** [comment]
the edges of the icons are cut off:

<img width="736" alt="Screenshot 2023-06-26 at 20 32 55" src="https://github.com/COPIM/open-book-collective/assets/120570478/1a22ae19-ac38-4467-81b1-8b31daccdc16">

**Comment by joedeville** [comment]
Ah right.. but that's deliberate, no? I think they all look ok to me apart from maybe the last one, where the edge of the loudhailer is trimmed a bit awkwardly

**Comment by MartinPaulEve** [comment]
Yes, this is by design as per original design spec
