### ISSUE TITLE
Authors from your institution

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#84]
In the checkout process, collect the institution name from a drop down, related to Thoth field. As part of the quote process (in a manner still to be determined) provide a list of authors from the chosen institution as a way of selling the OBC. 

Note: this is something we may want to build in structurally, but not necessarily make active yet -- as the metadata and number of publishers may need to improve

**Comment by joedeville** [comment]
May relate to #85

**Comment by joedeville** [comment]
I'm increasingly think this is *not* a good idea, as for many institutions there will be few authors.. which may act as a disintenctive to subscribing. It would be good to more efficiently be able to pull this info from Thoth -- but that's a Thoth issue!

**Comment by MartinPaulEve** [comment]
Just to add that I agree that this becomes really problematic; it incentivizes joining only when there's direct proven local benefit and for many institutions it will disincentivize. Closing.
