### ISSUE TITLE
Change dashboard login function

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#89]
Use only as a place to log in -- new accounts to be set up only by invitation from us (some libraries have been really confused by this area of the site)

**Comment by MartinPaulEve** [comment]
I don't quite understand this request - you _don't_ want libraries to be able to setup their own accounts without being invited? Seems like this adds another hoop for them to jump through for the whole thing, but if you want to do this we can just remove the link to setup own account

**Comment by joedeville** [comment]
@MartinPaulEve the thinking here is: we don't actually think libraries are in the near future going to need to access the backend to manage their subscriptions. But it may be in time that we use the backend for publishers/service providers to manage their pages etc. So we may want to be able to send them a link to set up their account. However, that doesn't need to be visible to any visitor to the site -- so better probably just to use this as a place to log in. So, in sum, yes I think remove link to set up own account (and ideally, provide a mechanism for someone to be able to set up an account if needed in the backend -- e.g. via sharing a link). We will figure out exactly what to do with the back end in due course (perhaps linked to a CRM / reminder type function)

**Comment by MartinPaulEve** [comment]
Addressed in https://github.com/COPIM/intrepid/commit/4dafdc34bff7a57553e7920c5a3f49930c3a0b83
