### ISSUE TITLE
On homepage, change 'Create Your Account' to 'Apply for Membership'

### ISSUE THREAD

**Issue by joedeville** [COPIM/open-book-collective#96]
And link to this page: 
https://www.openbookcollective.org/cms/fixed_page/why_support_oa/

[that's the correct URL at the moment. But really, the url needs to change to /membership]

**Comment by MartinPaulEve** [comment]
Fixed in https://github.com/COPIM/intrepid/commit/8ae387b7baaadb9101252a0fd6ef3345c50ad893
