### ISSUE TITLE
Quote and Acceptance form

### ISSUE THREAD

**Issue by francescacorazza** [COPIM/open-book-collective#99]
Users who have completed their details should receive via email the OBC quote along with the Acceptance form. Currently, the Acceptance form (word doc) and quote (pdf) are not attached to the email.
Here is the latest Acceptance form (changes to the previous version are highlighted in yellow):
[OBC_Acceptance_Form_.docx](https://github.com/COPIM/open-book-collective/files/12750419/OBC_Acceptance_Form_.docx)

Also, the subject line and email text are not correct. The text should be as follows:

Subject: OBC quotation details 

Many thanks for your interest in supporting Open Access book publishing. Your quotation is now complete and is attached to this email, with reference number [..]. This document also includes our Terms and Conditions for Supporting Institutions.

Please reply to this email should you wish to discuss further. Or, if you would like to go ahead and begin your Institution’s subscription, please complete the attached Acceptance Form, which we have partially pre-filled, and return it to us by replying to this email (or separately at info@openbookcollective.org).

If you have any questions, please do let us know.

Regards,

Open Book Collective

**Comment by ajrbyers** [comment]
The email template portion of this issu has been completed.

**Comment by francescacorazza** [comment]
This is the latest OBC Acceptance form:
[OBC_Acceptance_Form_-3.docx](https://github.com/COPIM/open-book-collective/files/13918552/OBC_Acceptance_Form_-2.docx)
